### ISSUE TITLE
燃料の自動補給

### ISSUE THREAD

**Issue by tomy-0000** [uec-world-dominators/computer-craft-tools#5]

**Comment by shosatojp** [comment]
`Navigator`に移動時hookを設定することで対応

使用イメージ

https://github.com/uec-world-dominators/computer-craft-tools/blob/8a458d2752ed5d43f1bccc9b9b125a87dac95246/dig#L65-L68


フックをセット

https://github.com/uec-world-dominators/computer-craft-tools/blob/8a458d2752ed5d43f1bccc9b9b125a87dac95246/dig#L74-L75

フック作成関数

https://github.com/uec-world-dominators/computer-craft-tools/blob/8a458d2752ed5d43f1bccc9b9b125a87dac95246/handlers.lua#L49
